### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by lpellegr** [wessberg/cjs-to-esm-transformer#2]
While trying to transform the following file using the CLI command:

https://github.com/marijnh/orderedmap/blob/master/index.js

I get the following error:

```
$ yarn run cjstoesm transform index.js dist
yarn run v1.19.1
$ /home/X/Projects/prosemirror-esm/orderedmap/node_modules/.bin/cjstoesm transform src/index.js test
(node:20706) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of undefined
    at Object.isExpressionNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/typescript/lib/typescript.js:11368:33)
    at isExpression (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:1743:15)
    at visitBinaryExpression (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:1898:97)
    at visitNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:2117:16)
    at ts.visitEachChild.cbNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:2388:37)
    at visitNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/typescript/lib/typescript.js:70904:23)
    at Object.visitEachChild (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/typescript/lib/typescript.js:71187:59)
    at Object.childContinuation (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:2387:23)
    at visitNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:2122:20)
    at ts.visitEachChild.cbNode (/home/X/Projects/prosemirror-esm/orderedmap/node_modules/@wessberg/cjs-to-esm-transformer/dist/cli/transform-task-29d3bc0d.js:2388:37)
(node:20706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wessberg** [comment]
Hey there. Thanks for reporting this issue. It has been fixed and released as part of [v0.0.13](https://github.com/wessberg/cjs-to-esm-transformer/releases/tag/v0.0.13).
