### ISSUE TITLE
Error: Export 'LRUMap' is not defined

### ISSUE THREAD

**Issue by moranje** [wessberg/cjs-to-esm-transformer#3]
[Continuing this conversation here...](https://github.com/wessberg/rollup-plugin-ts/issues/78)

Great! You know, if you keep helping me enough I will at eventually hit an error in the software you wrote :-). I think I have. With the above config and `v0.0.17` I now have the following error:

```
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/lru_map/lru.js: (1:9)
... (irrelevant)
[!] Error: Export 'LRUMap' is not defined
node_modules/lru_map/lru.js (1:9)
1: /**
      ^
2:  * A doubly linked list-based Least Recently Used (LRU) cache. Will keep most
3:  * recently used items while discarding least recently used items when its limit
Error: Export 'LRUMap' is not defined
    at error (/Users/martien/Sync/Projects/alfred-workflow-todoist/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/martien/Sync/Projects/alfred-workflow-todoist/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at tryParse (/Users/martien/Sync/Projects/alfred-workflow-todoist/node_modules/rollup/dist/shared/node-entry.js:9713:23)
    at Module.setSource (/Users/martien/Sync/Projects/alfred-workflow-todoist/node_modules/rollup/dist/shared/node-entry.js:10076:33)
    at /Users/martien/Sync/Projects/alfred-workflow-todoist/node_modules/rollup/dist/shared/node-entry.js:12362:20
    at async Promise.all (index 2)
    at async Promise.all (index 4)
    at async Promise.all (index 2)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
```

[LRU map](https://github.com/rsms/js-lru/blob/master/lru.js#L48) has a weird looking UMD factory, but I'm no expert. Is this something this library could/should fix?

**Comment by moranje** [comment]
For Reference: https://github.com/getsentry/sentry-javascript/issues/2364

**Comment by wessberg** [comment]
This library have very minimal support for UMD. Essentially, it is only meant to work with CommonJS, but just today I added basic support for UMD. Anyway, I took a look at it and fixed it. v0.0.18 is up now and includes the fix!

**Comment by moranje** [comment]
Thanks again for your wonderful help!
